### PR TITLE
Package lume in flatpak

### PR DESCRIPTION
**Pull request by kogeletey**
So, as this community has long asked, I will try to help with packaging the lume package in flatpak, [[IDEA] Distribution by flatpak · Issue #43 · luminous-devs/lume · GitHub](https://github.com/luminous-devs/lume/issues/43)
I’m not particularly experienced in packaging in this format, so if someone gives me some good advice, I’ll take it into account. 
I saw that version 3 is being prepared here, I hope that I will be in time for it)

### CODE REVIEW

**Comment by reyamir** [comment]
Amazing, this is huge news 🔥
I will merge it into v3 too

**Comment by reyamir** [comment]
I'm also posted 200K sats bounty for flatpak before, despite it expired but you can send me your lightning address, I will send this bounty to you

**Comment by kogeletey** [comment]
> I'm also posted 200K sats bounty for flatpak before, despite it expired but you can send me your lightning address, I will send this bounty to you

Let's do the task first, and only then think about payment

**Comment by kogeletey** [comment]
Two days later I was able to assemble the flatpak. Try, test and report errors if there any.

[lume-x86_64.zip](https://github.com/luminous-devs/lume/files/13869499/lume-x86_64.zip)

**Comment by reyamir** [comment]
Thank you for hard work, I will testing it at tonight

**Comment by kogeletey** [comment]
In general, everything seems to be the same.
I'll compress the commits to one after all the bugs are fixed  and remove the draft status.
Latest version of flatpack: 
[lume-x86_64.zip](https://github.com/luminous-devs/lume/files/13874260/lume-x86_64.zip)
My ligthing adress: 0x537de8f345b18995@ln.tips

If there are any problems, I’ll look into [nostr](https://nostree.me/npub1hxvh4tfvu2l2xyyhe9ph4kdhe0vycw6hsfem9mefm2yge635wunqh228ml) or [telegram](0x537de8f345b1899) personally.

**Comment by reyamir** [comment]
Yo, other user also tested your flatpak, it run really well

**Comment by kogeletey** [comment]
It's good.  I'm waiting for the implementation of the third version, and I will test it on it.
After all the mistakes, we will merge it into the ~~master~~ main branch.

**Comment by kogeletey** [comment]
I continue preparing version 3 for the flatpak version.  We will also need to check how release actions work -  after the merger into master we won't release it right away @reyamir?

**Comment by reyamir** [comment]
oh, sorry you I've missed your comment. I've tested flatpak for v3 and it work pretty well
I also merged `next` branch into `main`. I not sure we can merged both CI actions into one, but keep it seperate is fine too.

Here are some screenshots you can add to installation screen
Screenshot 2024-01-21 at 16 46 37
Screenshot 2024-01-21 at 16 46 49
Screenshot 2024-01-21 at 16 46 56

**Comment by kogeletey** [comment]
I have almost the everything ready, but I haven't tested depot yet.
As I understand, it completely removed

**Comment by reyamir** [comment]
Hi, you ignore depot, I will make it optional, if user need that feature, they will download additional package in-app, not need to embed in default app, it will make the package larger

**Pull request merged**
